AJ-945 - Auto update WDS version in terra helm file (#231)

diff --git a/.github/workflows/publish-docker.yml b/.github/workflows/publish-docker.yml
--- a/.github/workflows/publish-docker.yml
+++ b/.github/workflows/publish-docker.yml
@@ -100,4 +100,33 @@ jobs:
           echo ${{ secrets.ACR_SP_PASSWORD }} | docker login ${ACR_REGISTRY} \
           --username ${{ secrets.ACR_SP_USER }} \
           --password-stdin
-          docker push --all-tags ${{ steps.acr-image-name.outputs.name }}
+          
+      - name: Clone terra-helmfile
+        uses: actions/checkout@v3
+        with:
+          repository: broadinstitute/terra-helmfile
+          token: ${{ secrets.BROADBOT_TOKEN }} # Has to be set at checkout AND later when pushing to work
+          path: terra-helmfile
+          
+      - name: Create terra-helmfile PR for latest WDS version
+        env:
+          BROADBOT_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
+          GH_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
+        run: |
+          set -e
+          JIRA_ID=${{ steps.find-jira-id.outputs.JIRA_ID }}
+          if [[ $JIRA_ID == "missing" ]]; then
+            echo "JIRA_ID missing, PR to terra-helmfile will not be created"
+            exit 0;
+          fi
+          cd terra-helmfile
+          HELM_CUR_TAG=$(grep "/terra-workspace-data-service:" charts/wds/values.yaml | sed "s,.*/terra-workspace-data-service:,,")
+          HELM_NEW_TAG=${{ inputs.new-tag }}
+          git checkout -b ${JIRA_ID}-auto-update-${HELM_NEW_TAG}
+          [[ -n "$HELM_CUR_TAG" && -n "$HELM_NEW_TAG" ]]
+          sed -i "s/$HELM_CUR_TAG/$HELM_NEW_TAG/" charts/wds/values.yaml
+          git config --global user.name "broadbot"
+          git config --global user.email "broadbot@broadinstitute.org"
+          git commit -am "${JIRA_ID}: Auto update WDS version to $HELM_NEW_TAG"
+          git push -u origin ${JIRA_ID}-auto-update-${HELM_NEW_TAG}
+          gh pr create --title "${JIRA_ID}: auto update WDS version to $HELM_NEW_TAG" --body "${JIRA_ID} helm chart update" --label "automerge"
